config/routes.rb
# -*- coding: utf-8 -*-
Wordrobe::Application.routes.draw do
  match "/auth/facebook/callback" => "sessions#create", :as => "auth_provider_callback", :via => :get
  match "/log_out" => "sessions#destroy_with_ajax", :as => "log_out", :via => :delete

  match "/" => "static#welcome", :as => "welcome", :via => :get
  match "/dashboard" => "accounts#dashboard", :as => "dashboard", :via => :get
  match "/accounts" => "accounts#destroy_with_ajax", :as => "goodby", :via => :delete

  namespace :accounts do
    resources :wordrobes, :except => [:index, :show, :new, :create, :edit, :update, :destroy] do
      get :autocomplete_word_name, :on => :collection
      match "create", :action => "create_with_ajax", :as => "create", :via => :post, :on => :collection
      match "wordrobes", :action => "wordrobes_with_ajax", :as => "wordrobes", :via => :get, :on => :collection
      match "toggle_memorize", :action => "toggle_memorize_with_ajax", :as => "toggle_memorize", :via => :put, :on => :member
      match "toggle_translate", :action => "toggle_translate_with_ajax", :as => "toggle_translate", :via => :put, :on => :member
    end
  end
end

app/views/layouts/_add_modal.html.erb
<div id="add" class="modal hide fade my_modal">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3><%= t(".message.title") %></h3>
  </div>
  <div class="modal-body">
    <p><%= t(".message.intro") %></p>
    <%= form_tag "", :id => "add_form" do %>
      <%= autocomplete_field_tag "word", "", autocomplete_word_name_accounts_wordrobes_path %>
      <input type="button" value="<%= t(".button.create") %>" id="add_button" class="btn small" />
    <% end %>
  </div>
</div><!-- /#add -->

app/views/layouts/_error_modal.html.erb
<div id="error" class="modal hide fade my_modal">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3><%= t(".message.title") %></h3>
  </div>
  <div class="modal-body">
    <p id="message"></px>
  </div>
</div><!-- /#help -->

app/views/layouts/_help_modal.html.erb
<div id="help" class="modal hide fade my_modal">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3><%= t(".message.title") %></h3>
  </div>
  <div class="modal-body">
    <p><%= t(".message.subject.hotkey") %></p>
    <ul>
      <li><strong class="key">h</strong>&nbsp;<%= t(".message.body.help") %></li>
      <li><strong class="key">a</strong>&nbsp;<%= t(".message.body.add") %></li>
      <li><strong class="key">m</strong>&nbsp;<%= t(".message.body.memorize") %></li>
      <li><strong class="key">&#8593;</strong>&nbsp;<%= t(".message.body.translate") %></li>
      <li><strong class="key">&#8592;</strong>&nbsp;or&nbsp;<strong class="key">&#8594;</strong>&nbsp;<%= t(".message.body.navigate_per_one") %></li>
      <li><strong class="key">shift</strong>&nbsp;+&nbsp;<strong class="key">&#8592;</strong>&nbsp;or&nbsp;<strong class="key">shift</strong>&nbsp;+&nbsp;<strong class="key">&#8594;</strong>&nbsp;<%= t(".message.body.navigate_per_ten") %></li>
    </ul>
    <p><%= t(".message.subject.history") %></p>
    <ul>
      <li><%= t(".message.body.history") %>&nbsp;<span class="label"><%= t(".label.under_construction") %></span></li>
    </ul>
    <p><%= t(".message.subject.config") %></p>
    <ul>
      <li><%= t(".message.body.config") %>&nbsp;<span class="label"><%= t(".label.under_construction") %></span></li>
    </ul>
    <p><%= t(".message.subject.quit") %></p>
    <ul>
      <li><%= t(".message.body.quit") %></li>
    </ul>
  </div>
</div><!-- /#help -->

app/views/layouts/_privacy_modal.html.erb
<div id="privacy" class="modal hide fade my_modal">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3><%= t(".message.title") %></h3>
  </div>
  <div class="modal-body">
    <p><%= t(".message.subject.your_data") %></p>
    <ul>
      <li><%= t(".message.body.facebook_id") %></li>
      <li><%= t(".message.body.facebook_nickname") %></li>
      <li><%= t(".message.body.facebook_name") %></li>
      <li><%= t(".message.body.wordrobes") %></li>
    </ul>
    <p><%= t(".message.subject.not_stored_data") %></p>
    <ul>
      <li><%= t(".message.body.privacy_items") %></li>
    </ul>
    <% if current_account %>
      <p><%= simple_format t(".message.subject.withdraw_for_user") %></p>
      <ul>
        <li><a href="#" id="withdraw_link"><%=t(".message.link.withdraw") %></a>&nbsp;<span class="label important"><%=t(".label.withdraw") %></span></li>
      </ul>
    <% else %>
      <p><%= simple_format t(".message.subject.withdraw_for_guest") %></p>
    <% end %>
  </div>
</div><!-- /#help -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wordrobe</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="<%= controller_name + "_" + action_name %>" class="<%= controller_name %> <%= action_name %>">
  <div id="header">
    <div class="container">
      <h1 id="logo"><%= link_to "Wordrobe", welcome_path %></h1>
    </div><!-- /.container -->
  </div><!-- /#header -->

  <%= yield %>

  <div id="footer">
    <div class="container">
      <div id="link">
        <% if current_account %>
          <a href="#" id="history_link" title="<%= t(".link.history") %>"><%= t(".link.history") %></a>
          <a href="#" id="config_link" title="<%= t(".link.config") %>"><%= t(".link.config") %></a>
          <a href="#" id="help_link" title="<%= t(".link.help") %>"><%= t(".link.help") %></a>
        <% end %>
        <a href="#" id="privacy_link" title="<%= t(".link.privacy") %>"><%= t(".link.privacy") %></a>
        <% if current_account %>
          <%= link_to t(".link.log_out"), log_out_path, :method => :delete %>
        <% end %>
      </div>
      <div id="copyright">&copy; MARUGOSHI.ORG</div>
    </div><!-- /.container -->
  </div><!-- /#footer -->
</div><!-- /#<%= controller_name + "_" + action_name %> .<%= controller_name %> .<%= action_name %> -->

<%= render :partial => "layouts/privacy_modal" %>
<% if current_account %>
  <%= render :partial => "layouts/help_modal" %>
  <%= render :partial => "layouts/add_modal" %>
  <%= render :partial => "layouts/error_modal" %>
<% end %>
</body>
</html>